/* Author: Martin Sigley  3/15/2021

This has not been fully tested yet, as with most of my programs...lol Errors are possible. If you find an incorrect character in the output file, you can correct it in the array very easily, just locate the incorrect entry by following the remark statements and change. If I find errors or errors are reported to me I will apply the fixes in updates to this file.

Usage info: To use is very easy, you can drag and drop a c source file on to this program from windows and it will auto convert or you can type the name of the source file on the command line when running the program. Alternatively, you can also just run the program and input both source and destination file names at the prompts. Wild cards are NOT supported at this time. All source files must end with .seq, which is the naming convention used by the program Dirmaster when files are extracted from disk images, this limitation pertains only to names entered on the commandline, not by the prompts. All autogenerated output file names will have the .seq removed. If you use the prompts you can use any file names you like for both source and destination files.

Bonum diem habeas! :)
*/

#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <string.h>
#include <ctype.h>

#define MAX_NAME_LEN 100
#define BUFSIZE 65536

/* 
Conversion array, for PETSCII Power C source files to  ASCII files. You only have to change a few defintions to be PETSCII compatible. This array is based off of Scancode set 2, upper and lower case letters not the default upper case only letters found in Scancode set 1.
*/

char pc2asc[] =
{      /*   0     1     2     3      4 */
      /*   ----------------------------*/
/*   0 */   0,     0,    0,    0,    0,
/*   5 */   0,     0,    0,    0,    0,
/*  10 */   0,     0,    0,   10,    0,
/*  15 */   0,     0,    0,    0,    0,
/*  20 */   0,     0,    0,    0,    0,
/*  25 */   0,     0,    0,    0,    0,
/*  30 */   0,     0,    32, '!',   34,
/*  35 */ '#',   '$',   '%', '&', '\'',
/*  40 */  40,    41,   '*', '+',  ',',
/*  45 */  '-',  '.',   '/', '0',  '1',
/*  50 */  '2',  '3',   '4', '5',  '6',
/*  55 */  '7',  '8',   '9', ':',  ';',
/*  60 */  '<',  '=',   '>', '?',  '@',
/*  65 */  'a',  'b',   'c', 'd',  'e',
/*  70 */  'f',  'g',   'h', 'i',  'j',
/*  75 */  'k',  'l',   'm', 'n',  'o',
/*  80 */  'p',  'q',   'r', 's',  't',
/*  85 */  'u',  'v',   'w', 'x',  'y',
/*  90 */  'z',   91,  '\\',  93,  '^',
/*  95 */   0,     0,    0,    0,    0,
/* 100 */   0,     0,    0,    0,    0,
/* 105 */   0,     0,    0,    0,    0,
/* 110 */   0,     0,    0,    0,    0,
/* 115 */   0,     0,    0,    0,    0,
/* 120 */   0,     0,    0,    0,    0,
/* 125 */   0,     0,    0,    0,    0,
/* 130 */   0,     0,    0,    0,    0,
/* 135 */   0,     0,    0,    0,    0,
/* 140 */   0,     0,    0,    0,    0,
/* 145 */   0,     0,    0,    0,    0,
/* 150 */   0,     0,    0,    0,    0,
/* 155 */   0,     0,    0,    0,    0,
/* 160 */   0,     0,    0,    0,    0,
/* 165 */   0,     0,    0,    0,    0,
/* 170 */   0,     0,    0,    0,    0,
/* 175 */   0,     0,    0,    0,    0,
/* 180 */   0,     0,    0,    0,    0,
/* 185 */   0,     0,    0,    0,    0,
/* 190 */   0,     0,    0,  'A',  'B',
/* 195 */  'C',  'D',  'E',  'F',  'G',
/* 200 */  'H',  'I',  'J',  'K',  'L',
/* 205 */  'M',  'N',  'O',  'P',  'Q',
/* 210 */  'R',  'S',  'T',  'U',  'V',
/* 215 */  'W',  'X',  'Y',  'Z',  123,
/* 220 */   0,   125,    0,  '|',    0,
/* 225 */   0,     0,    0,    0,    0,
/* 230 */   0,     0,    0,    0,    0,
/* 235 */   0,     0,    0,    0,    0,
/* 240 */   0,     0,    0,    0,    0,
/* 245 */   0,     0,    0,    0,    0,
/* 250 */   0,     0,    0,    0,    0,
/* 255 */   0
};

void convert(char *ifname, char *ofname);
void quit( void );

FILE *lf;

int main( int argc, char **argv)
{
	char ifname[MAX_NAME_LEN], ofname[MAX_NAME_LEN], kbi;
	
	puts("");

    lf = fopen("pc2asc.log", "w");
	
    while(--argc)
	{
		if(strstr(argv[argc], ".seq"))
		{
			strcpy(ifname, argv[argc]);
			strcpy(ofname, argv[argc]);
			ofname[(unsigned) (strstr(argv[argc], ".seq") - argv[argc])] = '\0';
		}
		else
		{
			fprintf( lf, "\nERROR: Inorrect file type. Filename must end with: .seq\n%s\n", argv[argc]);
			
			if(argc > 1)
				continue;
			
			quit();
		}
		
		fprintf(lf, "\nProcessing %s...\n", ifname);
		convert(ifname, ofname);
		fprintf(lf, "\n%s completed successfully!\nOutput file name: %s\n", ifname, ofname);
		
		if(1 == argc)
			quit();
	}
	
	puts("Enter source file name:");
	fgets(ifname, MAX_NAME_LEN - 1, stdin);
	puts("Enter destination file name.");
	fgets(ofname, MAX_NAME_LEN - 1, stdin);

	/* Delete the RETURN character 13 from string */
	ifname[strlen(ifname)-1] = '\0';
	ofname[strlen(ofname)-1] = '\0';
	
	convert(ifname, ofname);
	
	fprintf(lf, "\n%s completed successfully!\nOutput file name: %s\n", ifname, ofname);
	
	quit();
}

void convert(char *ifname, char *ofname)
{
    FILE *fp;
    size_t bytesread;
    static char overwrite = 1, kbi;
    unsigned char data[BUFSIZE];
	
	if(overwrite)
	{
		if(NULL != (fp = fopen(ofname, "r")))
		{
			fclose(fp);
			printf("Output file name: %s\nAlready exists. Overwrite (Yes/No/All) ", ofname);
			kbi = toupper(getch());
			
			switch(kbi)
			{
				case 'A':
					overwrite = 0;
					break;
				case 'Y':
					break;
				default:
					return;
					break;
			}
		}
	}		

	if(NULL == (fp = fopen(ifname, "r")))
	{
		fprintf(lf, "%s: Failed to open source file.\n", ifname);
		return;
	}
	
	if(1 > (bytesread = fread(data, sizeof(char), BUFSIZE, fp)))
	{
		fprintf(lf, "%s: Failed to read source file.", ifname);
		return;
	}

	fclose(fp);
	
	/* Convert PETSCII to ASCII */
	for(int a = 0; a < bytesread; a++)
	{
		data[a] = pc2asc[data[a]];
		fputc(data[a], lf);
		
		if(13 != data[a])
			putchar(data[a]);
		else
		{
			puts("");
		}			
	}

	if(NULL == (fp = fopen(ofname, "w")))
	{
		fprintf(lf, "%s: Error opening file for write.", ofname);
		return;
	}

	if(fwrite(data, sizeof(char), bytesread, fp) < 1)
		fprintf(lf, "%s: Failed to write to destination file.", ofname);
	
	fclose(fp);
}

void quit( void )
{
	fclose(lf);
	exit(0);
}